### ISSUE TITLE
feat: automatic refresh of the `ingress rules` page

### ISSUE THREAD

**Issue by tanmoysrt** [swiftwave-org/swiftwave-dashboard#30]
### Is your feature request related to a problem? Please describe

Currently, one must manually click the refresh button to refresh the ingress rules page.

### Describe the solution you'd like

1. The page sould be refreshed after a ceratin interval (10 seconds).
2. During refreshing, there should be a spinner in the refresh button.

### Additional context

 
![image](https://github.com/swiftwave-org/swiftwave-dashboard/assets/80196675/d5058c89-653f-4264-864d-c7fd64af71bf)

### Are you working on this?

No

**Comment by ChavvaNarayana** [comment]
Sounds good to me. I'm willing to contribute.
Please assign it to me.

**Comment by tanmoysrt** [comment]
> Sounds good to me. I'm willing to contribute. Please assign it to me.

You have been assigned issue #27 . We can only provide a single issue, still not closing issue to give some chance to other contributor as well.

**Comment by TMuthu** [comment]
I would like to work on this. please assign to me.

**Comment by tanmoysrt** [comment]
> I would like to work on this. please assign to me.

Sure, go ahead

**Comment by tanmoysrt** [comment]
@TMuthu  Welcome to SwiftWave Community, Star :star: [the main repository [swiftwave]](https://github.com/swiftwave-org/swiftwave) to grow this project and join our slack community [[invite link](https://join.slack.com/t/swiftwave-team/shared_invite/zt-21n86aslx-aAvBi3hv1GigVA_XoXiu4Q)] to stay updated.
