### ISSUE TITLE
feat: automatic refresh of the `redirect rules` page

### ISSUE THREAD

**Issue by tanmoysrt** [swiftwave-org/swiftwave-dashboard#32]
### Is your feature request related to a problem? Please describe

One must manually click the refresh button to refresh the redirect rules page.

### Describe the solution you'd like

1. The page should be refreshed after a certain interval (10 seconds).
2. During refreshing, there should be a spinner in the refresh button.

### Additional context

 ![image](https://github.com/swiftwave-org/swiftwave-dashboard/assets/80196675/d5058c89-653f-4264-864d-c7fd64af71bf)

### Are you working on this?

No

**Comment by ChavvaNarayana** [comment]
Sounds good to me. I'm willing to contribute.
Please assign it to me.

**Comment by tanmoysrt** [comment]
> Sounds good to me. I'm willing to contribute. Please assign it to me.

You have been assigned issue #27 . We can only provide a single issue, still not closing issue to give some chance to other contributor as well.

**Comment by tanmoysrt** [comment]
@TMuthu you have been assigned this issue as well because your PR covers this as well.
