### ISSUE TITLE
feat: auto-rectify git source url

### ISSUE THREAD

**Issue by cAmartya** [swiftwave-org/swiftwave-dashboard#36]
### Is your feature request related to a problem? Please describe

Currently, if a user enters an extended GitHub URL instead of the repository URL. 
For example, `https://github.com/SwiftWave/SwiftWave/tree/main` instead of `https://github.com/SwiftWave/SwiftWave`, then an invalid GitHub credentials alert is displayed. 

### Expected Changes
The input field should auto-rectify the URL by converting the provided one to the required specification.

### Describe the solution you'd like
1. Trim the extra URL. URL should be of the form ```https://github.com/{User | Organization}/{Repository}``` 

### Describe alternatives you've considered
1. You can use regex to verify and fix the URL
2. Also make sure, the URL can be of github, gitlab or bitbucket. 

### Additional context

![image](https://github.com/swiftwave-org/swiftwave-dashboard/assets/80196675/a34bc63d-f5e2-402f-ade8-5c8e13e07b0c)

### Are you working on this?

No

**Comment by avelynhc** [comment]
@tanmoysrt  hello, I want to work on this issue. Can you assign it to me? Thanks!

**Comment by tanmoysrt** [comment]
@avelynhc sure 👍. Go ahead

**Comment by avelynhc** [comment]
@tanmoysrt Hi, I can't seem to pass the login page at the moment. Is is just me? Let me know. Thanks!

<img width="508" alt="Screenshot 2023-09-28 at 4 09 25 PM" src="https://github.com/swiftwave-org/swiftwave-dashboard/assets/75185537/59bfc79c-c5f9-4ef5-ba83-d42a62497b0c">

**Comment by tanmoysrt** [comment]
@avelynhc  Welcome to SwiftWave Community, Star :star: [the main repository [swiftwave]](https://github.com/swiftwave-org/swiftwave) to grow this project and join our slack community [[invite link](https://join.slack.com/t/swiftwave-team/shared_invite/zt-21n86aslx-aAvBi3hv1GigVA_XoXiu4Q)] to stay updated.
