### ISSUE TITLE
bug: SSL certificate fullchain textarea should be editable

### ISSUE THREAD

**Issue by tanmoysrt** [swiftwave-org/swiftwave-dashboard#40]
### Issue
In SSL Certificate details modal, the full chain textarea is editable.
![image](https://github.com/swiftwave-org/swiftwave-dashboard/assets/57363826/658f1f8f-83a0-410a-80d1-33f883390e84)

### Expected Behaviour
The textarea should be read-only and have a background of disabled textarea kind o

**Comment by aybeedee** [comment]
Hi, would like to work on this, can I kindly be assigned?

**Comment by tanmoysrt** [comment]
> Hi, would like to work on this, can I kindly be assigned?

sure go ahead :+1:

**Comment by tanmoysrt** [comment]
@aybeedee  Welcome to SwiftWave Community, Star :star: [the main repository [swiftwave]](https://github.com/swiftwave-org/swiftwave) to grow this project and join our slack community [[invite link](https://join.slack.com/t/swiftwave-team/shared_invite/zt-21n86aslx-aAvBi3hv1GigVA_XoXiu4Q)] to stay updated.
