### ISSUE TITLE
add workbox

### ISSUE THREAD

**Issue by tanmoysrt** [swiftwave-org/swiftwave-dashboard#79]
The website has little bit more JS files. To improve loading speed, make it as PWA with workbox
Guide - https://blog.logrocket.com/frontend-caching-in-vue-with-workbox-service-workers/

**Comment by TouchstoneTheDev** [comment]
Assign this to me

**Comment by tanmoysrt** [comment]
> Assign this to me

Sure ! You can checkout https://swiftwave.org/ for installation info, also can join the slack channel https://slack.swiftwave.org/

**Comment by tanmoysrt** [comment]
Not required anymore due to `cache-control` and `e-tag` implementation at server end.
Ref - https://github.com/swiftwave-org/swiftwave/pull/627
